services:
  redis:
    image: redis:8
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redisdata:/data

  postgres-test:
    image: postgres:18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ustudy_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ustudy_test"]
      interval: 1s
      timeout: 5s
      retries: 10
